mantraml/ui/core/models.py
import boto3
from collections import Counter
import datetime
import os
import shutil
import yaml

from django.db import models

from .consts import MANTRA_DEVELOPMENT_TAG_NAME
from .mantra import Mantra
from .forms import StartInstanceForm, StopInstanceForm, TerminateInstanceForm


class Cloud:

    @classmethod
    def change_instance_state(cls, ec2_resource, POST):
        """
        This method changes the state of an instance based on the request of an instance form view.

        Parameters
        ------------

        ec2_resource - boto3.resource('ec2') instance
            The EC2 connection

        POST - request.POST object
            Containing the form information
        """

        if 'stop_instance_id' in POST.dict():
            posted_form = StopInstanceForm(POST)
            if posted_form.is_valid():
                instance_id = posted_form.cleaned_data['stop_instance_id']
                ec2_resource.instances.filter(InstanceIds=[instance_id]).stop()
        elif 'start_instance_id' in POST.dict():
            posted_form = StartInstanceForm(POST)
            if posted_form.is_valid():
                instance_id = posted_form.cleaned_data['start_instance_id']
                ec2_resource.instances.filter(InstanceIds=[instance_id]).start()
        else:
            posted_form = TerminateInstanceForm(POST)
            if posted_form.is_valid():
                instance_id = posted_form.cleaned_data['terminate_instance_id']
                ec2_resource.instances.filter(InstanceIds=[instance_id]).terminate()

    @classmethod
    def get_instance_metadata(cls, instances, no_dev=False):
        """
        This method obtains instance metadata from a list of instances

        Parameters
        ------------

        instances - ec2.instances.filter object
            EC2 instance filter

        no_dev - bool
            If True, excludes development instances.

        Returns
        ------------
        list of dicts - list of instance metadata
        """

        instance_data = []

        for instance in instances:
            instance_dict = {}

            if instance.tags:
                instance_dict['name'] = instance.tags[0]['Value']
            else:
                instance_dict['name'] = ''

            instance_dict['type'] = instance.instance_type
            instance_dict['id'] = instance.id
            instance_dict['tags'] = []
            instance_dict['state'] = instance.state['Name']
            instance_dict['launch_time'] = instance.launch_time

            if no_dev:
                if instance_dict['name'] != MANTRA_DEVELOPMENT_TAG_NAME:
                    instance_data.append(instance_dict)
            else:
                if instance_dict['name'] == MANTRA_DEVELOPMENT_TAG_NAME:
                    instance_dict['tags'] += ['development']
                instance_data.append(instance_dict)

        return instance_data


class Trial:

    column_names = ['start_timestamp', 'folder_name', 'trial_hash', 'trial_group_hash', 'model_name', 'model_hash', 'data_name', 'data_hash', 'task_name', 'task_hash']

    @classmethod
    def get_trial_contents(cls, settings):
        """
        This method opens the TRIALS metadata file in the .mantra folder and obtains each row of trial metadata

        Parameters
        ------------

        settings - django.settings file
            Containing information like the MANTRA_PROJECT_ROOT constant

        Returns
        ------------

        list - list of trials each being a list of metadata (str format)
        """
        trial_information = open("%s/.mantra/TRIALS" % settings.MANTRA_PROJECT_ROOT, 'r').read()
        return [line.split(" ") for line in trial_information.split("\n") if line]

    @classmethod
    def get_trial_contents_as_dicts(cls, settings):
        """
        This method opens the TRIALS metadata file in the .mantra folder and obtains each row of trial metadata.
        It then converts this data into a list of dictionaries, where the keys come from Trial.column_names

        Parameters
        ------------

        settings - django.settings file
            Containing information like the MANTRA_PROJECT_ROOT constant

        Returns
        ------------

        list of dicts - each dictionary containing keys (cls.column_names) and values (from the file)
        """
        
        trial_contents = cls.get_trial_contents(settings=settings)
        return [dict(zip(cls.column_names, content)) for content in trial_contents]

    @classmethod
    def remove_group_hash_from_contents(cls, settings, trial_group_hash):
        """
        This method takes a trial contents object - a list of metadata - and removes rows where the group trial hash == trial_group_hash

        Parameters
        ------------
        settings - django.settings file
            Containing information like the MANTRA_PROJECT_ROOT constant

        group_trial_hash - str
            The hash of a group trial
        """

        trial_contents = cls.get_trial_contents(settings=settings)

        new_contents = [trial for trial in trial_contents if not trial[3] == trial_group_hash]
        trial_folder_names = [trial[1] for trial in trial_contents if trial[3] == trial_group_hash]
        new_information = '\n'.join([" ".join(content) for content in new_contents]) + '\n'

        for trial_folder in trial_folder_names:
            try:
                shutil.rmtree('%s/%s/%s' % (settings.MANTRA_PROJECT_ROOT, 'trials', trial_folder)) # delete the trial folder
            except FileNotFoundError:
                continue # if it's not there, it's already deleted, so we can proceed to try to solely remove from TRIALS file

        with open("%s/.mantra/TRIALS" % settings.MANTRA_PROJECT_ROOT, "w") as trial_file:
            trial_file.write(new_information)

    @classmethod
    def get_trial_group_members(cls, settings, model_filter=None, data_filter=None):
        """
        This method takes a trial contents object - a list of metadata - and removes rows where the group trial hash == trial_group_hash

        Parameters
        ------------
        settings - django.settings file
            Containing information like the MANTRA_PROJECT_ROOT constant
    
        model_filter - None or str
            If str, will filter the trials so that the trial['model_name'] == model_filter

        data_filter - None or str
            If str, will filter the trials so that the trial['data_name'] == data_filter

        Returns
        ------------
        dict - key is a trial group hash, value is a list of trials (dict metadata) that correspond to that trial group hash
        list - of trials
        """
        
        trials = cls.get_trial_contents_as_dicts(settings=settings)

        if model_filter:
            trials = [trial for trial in trials if trial['model_name'] == model_filter]
        elif data_filter:
            trials = [trial for trial in trials if trial['data_name'] == data_filter]

        trial_group_hashs = list(set([model['trial_group_hash'] for model in trials]))
        
        trial_group_dict = {trial_group_hash: [trial for trial in trials if trial['trial_group_hash'] == trial_group_hash] for trial_group_hash in trial_group_hashs}

        return trial_group_dict, trials

    @classmethod
    def get_trial_group_name_dict(cls, settings):
        """
        This method retrieves a dictionary with keys as trial group names, and values as string names for these ids. E.g.:

        {'ae42j2ff42f2jeduj4': 'Dropout Experiments'}

        This allows for trial groups to be named with human names, rather than dehumanising SHA-256 hashes.

        Parameters
        ------------
        settings - django.settings file
            Containing information like the MANTRA_PROJECT_ROOT constant

        Returns
        ------------
        dict - key is a trial group hash, value is a name for the trial group e.g. "Learning Rate Tests"
        """

        with open("%s/.mantra/TRIAL_GROUP_NAMES" % settings.MANTRA_PROJECT_ROOT, "r") as trial_group_name_file:

            yaml_content = yaml.load(trial_group_name_file)

            if not yaml_content:
                yaml_content = {}

        return yaml_content

    @staticmethod
    def get_trial_group_name(trial_group_name_dict, trial_group_hash):
        """
        Parameters
        ------------
        trial_group_name_dict - dict
            The dictionary containing as keys trial group hashes, and as values trial group names, e.g. "Dropout Experiments"

        trial_group_hash - str
            The string for the trial group hash, e.g. a93idjj4v2ojf42of24cew...
        
        Returns
        ------------
        str - the name of the trial group given the dictionary and the hash entered
        """

        try:
            return trial_group_name_dict[trial_group_hash]
        except KeyError:
            return trial_group_hash[:6]

    @classmethod
    def get_trial_group_metadata(cls, settings, hash, trial_groups):
        """
        This method obtains trial group metadata from a list of trial group dictionaries

        Parameters
        ------------
        settings - django.settings file
            Containing information like the MANTRA_PROJECT_ROOT constant
    
        hash - str
            The hash for the trial group

        trial_groups - list
            List of dicts, where each dict contains metadata on a trial

        Returns
        ------------
        dict - containing metadata on the trial group
        """

        yaml_content = Trial.get_trial_group_name_dict(settings=settings)

        latest_trial_time = datetime.datetime.utcfromtimestamp(int(str(max([trial['start_timestamp'] for trial in trial_groups]))))

        trial_group_metadata = {}

        if not trial_groups:
            return trial_group_metadata
        
        example_trial = trial_groups[0]

mantraml/ui/core/forms.py
from django import forms

class DeleteTrialForm(forms.Form):
    trial_hash = forms.CharField(widget = forms.HiddenInput(), label='trial_hash', max_length=64, required=False)

class DeleteTrialGroupForm(forms.Form):
    trial_group_hash = forms.CharField(widget = forms.HiddenInput(), label='trial_group_hash', max_length=64, required=False)

class StartInstanceForm(forms.Form):
    start_instance_id = forms.CharField(widget = forms.HiddenInput(), label='start_instance_id', required=False)

class StopInstanceForm(forms.Form):
    stop_instance_id = forms.CharField(widget = forms.HiddenInput(), label='stop_instance_id', required=False)

class TerminateInstanceForm(forms.Form):
    terminate_instance_id = forms.CharField(widget = forms.HiddenInput(), label='terminate_instance_id', required=False)

mantraml/ui/core/templates/datasets.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block contents %}




<div class="row title-row deck-break">
  <div style="float: left;" class="col-lg">
  <h1>Your Data</h1>
</div></div>

<div class="models-hold">
<table id="modeltable" class="table text-center">
  <thead>
    <tr>
      <th scope="col">Dataset</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>

    </tr>
  </thead>
  <tbody>


{% for dataset in datasets %}
    <tr>
      <td onclick="document.location = '/data/{{ dataset.folder_name }}'"><div class="model-name"><img src="/static/{{ dataset.data_image }}"> <a href="/data/{{ dataset.folder_name }}">{{ dataset.name }}</a></div></td>
      <td onclick="document.location = '/data/{{ dataset.folder_name }}'">
        {% for tag in dataset.tags %}
      <span class="badge badge-primary">{{ tag }}</span>
       {% endfor %}
     </td>
      <td onclick="document.location = '/data/{{ dataset.folder_name }}'"><div class="framework">
      {% if dataset.data_type == 'images' %}
      <i class="em em-frame_with_picture"></i>
      {% elif dataset.data_type == 'music' %}
      <i class="em em-musical_score"></i>
      {% else %}
      <i class="em em-floppy_disk"></i>
      {% endif %}
      </div></td>
      <td onclick="document.location = '/data/{{ dataset.folder_name }}'"><div class="date">{{ dataset.last_updated }}</div></td>
    </tr>
   {% endfor %}
  </tbody>
</table>


<script>
  $(document).ready(function () {
  $('#modeltable').DataTable( {
        "order": [[ 0, "asc" ]]
    } );
  $('.dataTables_length').addClass('bs-select');
});

$(document).on("click", ".open-deleteTrialGroupDialog", function () {
     var mytrialGroupId = $(this).data('id');
     $(".modal-content #id_trial_group_hash").val( mytrialGroupId );
});

</script>
</div>





{% endblock contents %}

mantraml/ui/core/templates/models.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block contents %}



      <div class="row title-row">
        <div style="float: left;" class="col-lg">
        <h1>Your Models</h1>
        </div>
        <div class="col-lg-4">

          <div style="float: right;" class="btn-group btn-group-sm pull-right" role="group" aria-label="Basic example">
           

          </div>
        </div>
      </div>

<div class="models-hold">

<div class="modal fade" id="deleteTrialGroupModal" tabindex="-1" role="dialog" aria-labelledby="deleteTrialGroupModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteTrialGroupModalLabel">Are you sure you want to delete this trial group?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="post">


    {% csrf_token %}
    {{ form }}

      <div class="modal-footer text-center">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
      </div>

</form>

    </div>
  </div>
</div>

<table id="modeltable" class="table text-center">
  <thead>
    <tr>
      <th scope="col">Model</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>



{% for model in models %}
    <tr>
      <td onclick="document.location = '/model/{{ model.folder_name }}'"><div class="model-name"><img src="/static/{{ model.image }}"> <a href="/model/{{ model.folder_name }}">{{ model.name }}</a></div></td>
      <td onclick="document.location = '/model/{{ model.folder_name }}'">
        {% for tag in model.tags %}
      <span class="badge badge-primary">{{ tag }}</span>
       {% endfor %}
     </td>
      <td onclick="document.location = '/model/{{ model.folder_name }}'"><div class="framework"><img src="/static/img/{{ model.framework }}.png"></div></td>
      <td onclick="document.location = '/model/{{ model.folder_name }}'"><div class="date">{{ model.last_updated }}</div></td>
    </tr>
   {% endfor %}



  </tbody>
</table>


<script>
  $(document).ready(function () {
  $('#modeltable').DataTable( {
        "order": [[ 0, "asc" ]]
    } );
  $('.dataTables_length').addClass('bs-select');
});

$(document).on("click", ".open-deleteTrialGroupDialog", function () {
     var mytrialGroupId = $(this).data('id');
     $(".modal-content #id_trial_group_hash").val( mytrialGroupId );
});

</script>

</div>




{% endblock contents %}

mantraml/ui/core/templates/results.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block contents %}



      <div class="row title-row">
        <div style="float: left;" class="col-lg">
        <h4>Your Results</h4>
        </div>
        <div class="col-lg-4">

          <div style="float: right;" class="btn-group btn-group-sm pull-right" role="group" aria-label="Basic example">
           

          </div>
        </div>
      </div>

<div class="trials-hold">

<div class="modal fade" id="deleteTrialGroupModal" tabindex="-1" role="dialog" aria-labelledby="deleteTrialGroupModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteTrialGroupModalLabel">Are you sure you want to delete this trial group?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="post">


    {% csrf_token %}
    {{ form }}

      <div class="modal-footer text-center">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
      </div>

</form>

    </div>
  </div>
</div>

<table id="trialgrouptable" class="table text-center">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Model</th>
      <th scope="col">Data</th>
      <th scope="col">Time</th>
    </tr>
  </thead>
  <tbody>


{% for result in results %}
    <tr>
      <td onclick="document.location = '/result/{{ result.folder_name }}'"><div class="model-name">
      {% if result.latest_media %}<img src="/static/{{ result.latest_media.file }}">{% else %}<img src="/static/img/default_model.jpg">{% endif %}<a href="/result/{{ result.folder_name }}">{{ result.name }}</a></div></td>
      <td onclick="document.location = '/result/{{ result.folder_name }}';"><img src="/static/{{ result.model_metadata.image }}"> <a href="/model/{{ result.model_metadata.folder_name }}">{{ result.model_metadata.name }}</a></td>
      <td onclick="document.location = '/result/{{ result.folder_name }}';"><img src="/static/{{ result.data_metadata.data_image }}"> <a href="/data/{{ result.data_metadata.folder_name }}">{{ result.data_metadata.name }}</a></td>
      <td onclick="document.location = '/result/{{ result.folder_name }}';">{{ result.last_updated }}</td>
    </tr>
   {% endfor %}
  </tbody>
</table>


<script>
  $(document).ready(function () {
  $('#trialgrouptable').DataTable( {
        "order": [[ 0, "desc" ]]
    } );
  $('.dataTables_length').addClass('bs-select');
});

$(document).on("click", ".open-deleteTrialGroupDialog", function () {
     var mytrialGroupId = $(this).data('id');
     $(".modal-content #id_trial_group_hash").val( mytrialGroupId );
});

</script>

</div>




{% endblock contents %}

mantraml/ui/core/templates/trials.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block contents %}



      <div class="row title-row">
        <div style="float: left;" class="col-lg">
        <h1>Your Trials</h1>
        </div>
        <div class="col-lg-4">

          <div style="float: right;" class="btn-group btn-group-sm pull-right" role="group" aria-label="Basic example">
           

          </div>
        </div>
      </div>

<div class="trials-hold">

<div class="modal fade" id="deleteTrialGroupModal" tabindex="-1" role="dialog" aria-labelledby="deleteTrialGroupModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteTrialGroupModalLabel">Are you sure you want to delete this trial group?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="post">


    {% csrf_token %}
    {{ form }}

      <div class="modal-footer text-center">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
      </div>

</form>

    </div>
  </div>
</div>

<table id="trialgrouptable" class="table text-center">
  <thead>
    <tr>
      <th scope="col">Time</th>
      <th hidden scope="col">Timestamp</th>
      <th scope="col">Trial Group</th>
      <th scope="col">Model</th>
      <th scope="col">Data</th>
      <th scope="col">Task</th>
      <th scope="col">Trials</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>


{% for trial_values in trial_groups %}
    <tr>
      <td onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';">{{ trial_values.time }}</td>
      <td hidden onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';">{{ trial_values.timestamp }}</td>
      <td onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';"><a href="/trials/{{ trial_values.trial_group_hash |slice:':6' }}">{{ trial_values.trial_group_name }}</a></td>
      <td onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';"><img src="/static/{{ trial_values.model_metadata.image }}"> {{ trial_values.model_metadata.name }}</td>
      <td onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';"><img src="/static/{{ trial_values.data_image }}"> {{ trial_values.data_full_name }}</td>
      <td onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';">
        {% if trial_values.task_full_name %}
        <i class="em em-chart_with_upwards_trend"></i> {{ trial_values.task_full_name }}
        {% else %}
        None
        {% endif %}
      </td>
      <td onclick="document.location = '/trials/{{ trial_values.trial_group_hash |slice:':6' }}';">{{ trial_values.n_trials }}</td>
      <td><button data-id="{{ trial_values.trial_group_hash }}" type="button" class="open-deleteTrialGroupDialog btn btn-primary" data-toggle="modal" data-target="#deleteTrialGroupModal">
        delete
      </button></td>
    </tr>
   {% endfor %}
  </tbody>
</table>


<script>
  $(document).ready(function () {
  $('#trialgrouptable').DataTable( {
        "order": [[ 1, "desc" ]]
    } );
  $('.dataTables_length').addClass('bs-select');
});

$(document).on("click", ".open-deleteTrialGroupDialog", function () {
     var mytrialGroupId = $(this).data('id');
     $(".modal-content #id_trial_group_hash").val( mytrialGroupId );
});

</script>

</div>




{% endblock contents %}

mantraml/ui/core/templates/view_trial_group.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% block contents %}

<div class="container content">

  <!-- Repo title and header -->
  <div class="row">

    <div class="col-md-2">
      <div class="data-trial-summary">
        <div class="data-trial-image"><img width=140 src="/static/{{ data.data_image }}"></div>
      </div>
    </div>

    <div class="col-md-8 trial-header">
      <div class="trial-section-header">
        <img src="/static/{{ model.image }}"> <a href="/model/{{ model.folder_name }}">{{ model.name }} </a>
        on 
        <img src="/static/{{ data.data_image }}"> <a href="/data/{{ data.folder_name }}">{{ data.name }}</a></div>
      
      <div class="main-header">{{ trial_group_name }}</div>
      <div class="latest-trial"><i class="em em-female-scientist"></i> Latest trial: {{ latest_trial }}</div>
    </div>
    <div class="col-md-2">
      <div class="repo-summary">
        <div class="repo-summary-image"><img width=140 src="/static/{{ model.image }}"></div>
      </div>
    </div>
  </div>




<div class="trials-hold">


<div class="modal fade" id="deleteTrialModal" tabindex="-1" role="dialog" aria-labelledby="deleteTrialModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteTrialModalLabel">Are you sure you want to delete this trial?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="post">


    {% csrf_token %}
    {{ form }}

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
      </div>

</form>

    </div>
  </div>
</div>

<table id="trialgrouptable" class="table text-center">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Epochs</th>
      <th scope="col">Trial ID</th>
      <th hidden scope="col">Timestamp</th>
      <th scope="col">Time</th>
      {% for hyperparm in hyperparms %}
      <th scope="col">{{ hyperparm | capfirst }}</th>
      {% endfor %}
      {% for metric_name in metric_names %}
      <th scope="col">{{ metric_name | capfirst }}</th>
      {% endfor %}
      {% if task_full_name %}
      <th scope="col">Evaluation Loss <ion-icon data-toggle="tooltip" title="{{ evaluation_name }}" name="information-circle-outline"></ion-icon></th>
      {% endif %}
      <th scope="col"></th>
    </tr>



  </thead>
  <tbody>



{% for trial_values in trials %}
    <tr>
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';"> {% if not trial_values.metadata.training_finished %}
        <img width=15 src="/static/img/live.gif">
        <script type="text/javascript">
        setTimeout(function () { location.reload(true); }, 60000);
       </script>
       {% else %}
       <i class="em em-white_check_mark"></i>
        {% endif %}</td>

      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">{{ trial_values.metadata.current_epoch }} / {{ trial_values.metadata.hyperparameters.epochs }}</td>
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">
      <a href="/trial/{{ trial_values.trial_hash |slice:':6' }}">{{ trial_values.trial_hash |slice:':6' }}</a></td>
      <td hidden onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">{{ trial_values.start_timestamp }}</td>
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">{{ trial_values.time }}</td>
      {% for hv in trial_values.hyperparm_values %}
      
      {% if hv.type == 'list' %}
      <td>
<div class="btn-group">
  <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    View List
  </button>
  <div class="dropdown-menu">
    {% for hyperparameter_item in hv.value %}
    <a class="dropdown-item small-dropdown-text" href="#">{{ hyperparameter_item }}</a>
    {% endfor %}
  </div>
</div>
      {% elif hv.type == 'float' %}
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">
      {{ hv.value|floatformat:4 }}
      {% else %}
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">
      {{ hv.value }}
      {% endif %}
      </td>
      {% endfor %}
      {% for mv in trial_values.metric_values %}
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">{{ mv|floatformat:4 }}</td>
      {% endfor %}
      {% if task_full_name %}
      <td onclick="document.location = '/trial/{{ trial_values.trial_hash |slice:':6' }}';">{{ trial_values.metadata.validation_loss |floatformat:4 }}</td>
      {% endif %}
      <td><button data-id="{{ trial_values.trial_hash }}" type="button" class="open-deleteTrialDialog btn btn-primary" data-toggle="modal" data-target="#deleteTrialModal">
  delete
</button></td>
    </tr>
   {% endfor %}
  </tbody>
</table>

<script>
  $(document).ready(function () {
  $('#trialgrouptable').DataTable( {
        "order": [[ 4, "desc" ]]
    } );
  $('.dataTables_length').addClass('bs-select');
});

$(document).on("click", ".open-deleteTrialDialog", function () {
     var mytrialId = $(this).data('id');
     $(".modal-content #id_trial_hash").val( mytrialId );
});

$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});

</script>

</div>



{% endblock %}

mantraml/ui/core/templates/view_trial_tensorboard.html
{% extends 'base_flex.html' %}
{% load staticfiles %}
{% load static %}
{% block contents %}

<div class="content">
<iframe src="http://localhost:6006/"></iframe>
</div>

<script type="text/javascript">
setTimeout(function () { location.reload(true); }, 300000);
</script>

{% endblock %}